### ISSUE TITLE
Automatizace nasazování

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/start-mozilla-cz#34]
Podobně jako https://github.com/MozillaCZ/l10n-mozilla-central-cs/tree/automation.

**Comment by MikkCZ** [comment]
Po clone by stačilo udělat push do git repa na hostingu. Jenom je potřeba [vypnout `--depth`](https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth).

**Comment by MikkCZ** [comment]
Alternativní řešení:
- přepsat do Jekyllu/Ruby
- použít pro hosting službu typu Netlify
- automaticky triggerovat build nějakým cronem pro aktualizaci RSS feedů a verze SM stahované z JSONu Mozilly

**Comment by MekliCZ** [comment]
@MikkCZ Když už jsou ty boxy psané v JS, co udělat nějaké jednoduché API, které necháme na ČH?

**Comment by MikkCZ** [comment]
Tím by se jen odsunul problém na nasazování API a navíc už bychom mohli rovnou to celé přepsat do JS. To mi ale nepřijde jako úplně dobrý nápad. U uživatelů SM je IMO velká šance, že budou mít JS vypnutý a pak by neviděli nic. Proto jsou pořád ty feedy zpracovávané na serveru a ne u klienta.

Nejjednodušší by bylo samozřejmě první řešení - pushování z Travise. Jenom jsem se k tomu ještě nedostal. ;)

**Comment by MikkCZ** [comment]
Teď mi došlo, že na Netlify apod. zřejmě nebudou fungovat věci jako [HSTS, CSP, XFO nebo Referrer-Policy](https://observatory.mozilla.org/analyze.html?host=start.mozilla.cz). Primární cesta by tedy měl být ten Travis build.

**Comment by MekliCZ** [comment]
10 sekund googlení: https://www.netlify.com/docs/headers-and-basic-auth/ 😄

**Comment by MikkCZ** [comment]
Vůbec jsem nečekal, že to půjde, takže jsem ani negooglil. Počítal jsem s věcmi, které umí vanilla Jekyll. Podívám se na to.

**Comment by MikkCZ** [comment]
Přepsal jsem to do Jekyllu a nasadit na Netlify. Aktualizace obsahu teď triggeruju od sebe, je nějaký problém s voláním hooku cronem z hostingu. Až se to podaří opravit (věřím, že dneska), bude to hotové.
