### ISSUE TITLE
Pořádně vertikálně zarovnat vyhledávání

### ISSUE THREAD

**Issue by MekliCZ** [MozillaCZ/start-mozilla-cz#36]
<img width="547" alt="snimek obrazovky 2017-12-29 v 20 32 45" src="https://user-images.githubusercontent.com/9162439/34445928-8c7e2342-ecd7-11e7-84c9-cf30e77168b7.png">

Teď to vypadá hrozně. @MikkCZ nemáš nic proti flexboxu? ;)

**Comment by MikkCZ** [comment]
Mám. Na start.mozilla.cz chodí lidé se starými verzemi SeaMonkey. Verze třeba z roku 2013 (Firefox 18) není nic výjimečného. IMO nemá cenu do start.mozilla.cz moc investovat a rozhodně ne si hrát na nějaké moderní technologie. ;)

**Comment by MekliCZ** [comment]
Flexbox není moderní technologie, s prefixem ho podporuje i Firefox 2. :D A je to práce na pět minut.

**Comment by MikkCZ** [comment]
No právě jenom s prefixem... Pořádně to tedy otestuj v SeaMonkey 2.0. 
https://archive.mozilla.org/pub/seamonkey/releases/2.0/mac/cs/

**Comment by MekliCZ** [comment]
Ještě mě napadlo, když už se použije ten flexbox (funguje i v SeaMonkey 2! 😄), což takhle roztáhnout to vyhledávací pole do „zbytkové“ šířky?

**Comment by MikkCZ** [comment]
Jen do toho.

**Comment by MekliCZ** [comment]
Roztáhnout se mi to ve starém SeaMonkey nepodařilo, ale vertikálně je to zarovnané skvostně.

**Comment by MikkCZ** [comment]
https://screenshots.firefox.com/lwsRLG9XynH47ewM/start.mozilla.cz

Hádám, že `width: auto` není správně.

**Comment by MikkCZ** [comment]
@MekliCZ Otestuj `width: 100%` prosím.

**Comment by MekliCZ** [comment]
@MikkCZ V SeaMonkey 2 nefunguje.

**Comment by MikkCZ** [comment]
Nasazeno.
