### ISSUE TITLE
Rozbitá SVG ve starém SeaMonkey

### ISSUE THREAD

**Issue by MekliCZ** [MozillaCZ/start-mozilla-cz#37]
V SeaMonkey 2 očividně nefungují SVG vložená přes `<img>`.

**Comment by MikkCZ** [comment]
Podle dokumentace je podpora až od Firefoxu 4 (Gecko 2.0), tj. SeaMonkey 2.1.

**Comment by MikkCZ** [comment]
Jak moc špatně to vypadá?

**Comment by MekliCZ** [comment]
Zobrazí se alt atribut (a nebo nic, pokud alt není - jako u loga)
<img width="622" alt="snimek obrazovky 2017-12-29 v 21 57 03" src="https://user-images.githubusercontent.com/9162439/34447354-3d4ab108-ece3-11e7-9fb9-b4bbf1cc0a34.png">

**Comment by MikkCZ** [comment]
Zkus tedy přidat `alt` pro logo (mozilla.cz) a `alt` ikonky DDG vyhoď. Bude to vypadat lépe?

**Comment by MekliCZ** [comment]
No, nemít `alt` je nevalidní. :D Logo alt nemá proto, že je jako CSS background, tzn. ho ani mít nemůže. Zkusím nějak elegantně vyřešit to logo DDG.

**Comment by MikkCZ** [comment]
Ajaja, obrázek jako CSS background. Přesně to, co nemám rád...

**Comment by MekliCZ** [comment]
No, já ho jako CSS background nenastavil. Ale u té hlavičky možná i dává smysl ho mít v CSS. Kolik lidí chodí na ten web v SM starším než 2.1?

**Comment by MikkCZ** [comment]
Cca 1 denně.

**Comment by MekliCZ** [comment]
@MikkCZ Napadá mě udělat něco takového:
`<img src="png" srcset="svg">`
Starý Firefox srcset nezná, takže použije to png co je v `src`, a ten nový použije SVG z srcsetu. Nevidím moc pravděpodobnost, že by staré SM používali lidi s vysokým DPI.

To samé můžu udělat u toho loga v hlavičce, ale musel bych ho přesunout z CSS.

**Comment by MikkCZ** [comment]
To už možná vyjde stejně dát tam PNG třeba v dvojnásobném rozlišení a 
nebudeme mít dva obrázky, nebo dát prázdný či velmi krátký `alt`. Vím, 
SVG je sexy...

Vyndat logo v hlavičce z CSS se mi líbí. U něj by IMO stačilo dát 
`alt="Mozilla.cz"` a všichni i starým SM budou spokojení.
