### ISSUE TITLE
Respektovat hlavičku DNT

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/start-mozilla-cz#38]
Pokud má hlavička [hodnotu `1`](https://www.w3.org/TR/tracking-dnt/#expressing), neměli bychom vkládat GA. A udělejme to klidně v JS.

**Comment by MekliCZ** [comment]
Klidně si to vezmu.

**Comment by MikkCZ** [comment]
`navigator.doNotTrack || window.doNotTrack` viz https://developer.mozilla.org/en-US/docs/Web/API/navigator/doNotTrack. Hodnoty, kdy GA nevkládat, jsou `"1"` a `"yes"`.

**Comment by MikkCZ** [comment]
Nasazeno a vypadá to, že funguje podle očekávání. :)
