### ISSUE TITLE
Nedostupný RSS feed zobrazí chybu

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/start-mozilla-cz#39]
Pokud RSS feed není dostupný, místo chyby "Nepodařilo se načíst RSS kanál." by se měla zobrazit jeho kešovaná verze. Problém v tuto chvíli nastává v okamžiku, kdy je starý obsah keše a aktualizace selže.

EDIT: Taky by bylo fajn keš v tu chvíli "přeuložit", abychom nebušili do nefunkčního feedu s každým načtením stránky, ale jenom jednou za interval platnosti keše bez ohledu na to, jestli se opravu stáhl nový obsah, nebo to selhalo. Bude se to také snáze implementovat.

**Comment by MekliCZ** [comment]
„starý obsah keše a aktualizace selže“ - je problém zobrazit starou cache a spolu s tím i nějaké upozornění, že obsah nemusí být aktuální? Ty články totiž pořád existují.

**Comment by MikkCZ** [comment]
> místo chyby "Nepodařilo se načíst RSS kanál." by se měla zobrazit jeho kešovaná verze

**Comment by MikkCZ** [comment]
IMO to má ale nízkou prioritu, protože teď je to způsobeno tím, že jsou ceskenoviny.cz opravdu dole.

**Comment by MekliCZ** [comment]
No to jo, ale potom nenastává problém ve chvíli, kdy je stará cache a aktualizace selže, ne?

**Comment by MikkCZ** [comment]
V tuto chvíli když je stará keš a aktualizace selže, zobrazí se chyba a keš se ignoruje. Co chci udělat je, aby v případě chyby se stále používala keš.

**Comment by MekliCZ** [comment]
Aha, trochu nejasně jsi to formuloval. Tohle je v pohodě. :)
