### ISSUE TITLE
Server push

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/start-mozilla-cz#40]
Mohli bychom tu vyzkoušet server push. Je to jen jedna stránka, takže nějaké krátké PHP a pole souborů to spraví. ;)

https://www.jakpsatweb.cz/server/http-2-server-push.html
https://www.netlify.com/blog/2017/07/18/http/2-server-push-on-netlify/

**Comment by MekliCZ** [comment]
Je potřeba, aby se hlavička Link poslala pro každý soubor zvlášť, teď jsou všechny v jedné hlavičce a (alespoň podle devtools) to nefunguje, i když se hlavička posílá. Opravím to.

**Comment by MikkCZ** [comment]
Všechno v jedné hlavičce je OK. Ve Firefoxu to v pohodě funguje, podle https://http2-push.io/ je taky všechno OK.
