### ISSUE TITLE
Sestavení na Netlify často selhává

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/start-mozilla-cz#44]
Párkrát se zasekl, ale co jsem zrovna proklikával, většinou byl problém se stažením JSONu s verzí SeaMonkey nebo instalací závislostí.

**Comment by MikkCZ** [comment]
Instalace závislostí je vyřešená fixní verzí Ruby. Bylo by fajn taky přidat `Gemfile.lock`.

**Comment by MikkCZ** [comment]
Dnes 5 selhání od 6:30 do 7:30, protože nefungoval feed Českých novin.

**Comment by MekliCZ** [comment]
Zkusil bych s tim prudit CTK, tohle je fakt nenormalni.Dne 2. 6. 2018 8:33 napsal uživatel Michal Stanke <notifications@github.com>:Dnes 5 selhání od 6:30 do 7:30, protože nefungoval feed Českých novin.

**Comment by MikkCZ** [comment]
Napíšu jim. Nám se ale podobný výpadek taky občas nevyhne. ;)

**Comment by MekliCZ** [comment]
Napadá mě, co si vyrobit nějaký vlastní cachovací script? Netlify by requestovalo ten a script by zkusil fetchnout aktuální data, když by se to nepodařilo, vrátil by poslední co zná. Pár řádků PHPka.

**Comment by MikkCZ** [comment]
Pracuji na tom. Myslím, že to půjde vyřešit i přímo na Netlify, případně vylepšením toho triggeru přes API. Pár řádků PHPka to kdyžtak jistí, ale bylo by lepší, kdyby to šlo i bez toho.

**Comment by MikkCZ** [comment]
Včerejší problém byl problém s resolvnutím seamonkey-project.org https://app.netlify.com/sites/start-mozilla-cz/deploys/5b1e80630733d512f7541428.

Už jsem se rozhodl, jaké bude řešení. Sestavení udělám jako Travis CI build, který má svou keš, a bude pushovat už hotový výsledek do větve. Možná ani tu cache nemusí používat a prostě to celé spolkne. Když se to udělá dobře, budou pořád fungovat i náhledy pull requestů.
